# Generated by Django 3.2.7 on 2021-12-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protest_data',
            name='outcomes',
        ),
    ]
