# Generated by Django 3.2.7 on 2022-01-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_protest_data_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='protest_data',
            name='media_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='protest_data',
            name='image_videos',
            field=models.FileField(blank=True, null=True, upload_to='protest_images/'),
        ),
        migrations.AlterField(
            model_name='protest_data',
            name='type_of_action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
