# Generated by Django 3.2.7 on 2022-01-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20220108_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protest_data',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='protest_data',
            name='size_of_protest',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
