# Generated by Django 3.2.7 on 2022-01-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20220108_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protest_data',
            name='likes_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='protest_data',
            name='retweets_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
