# Generated by Django 3.2.7 on 2022-01-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20220108_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protest_data',
            name='d_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
